const Map<String, int> venueCodes = {
  "All": 0,
  "Administrative Staff College of India Hyderabad": 18,
  "Convention Hall": 8,
  "Greater Noida Extension Centre of IIT Roorkee": 33,
  "Himachal Pradesh Institute of Public Administration Shimla": 10,
  "Indian Institute Of Management Bangalore": 46,
  "Indian Institute Of Management Indore": 14,
  "Indian Institute Of Management Kozhikode": 36,
  "Indian Institute Of Management Lucknow": 30,
  "Indian Institute Of Management Udaipur": 34,
  "Indian Institute Of Management Visakhapatnam": 48,
  "Indian Institute of Technology Delhi Sonipat Haryana Campus": 37,
  "Indian Institute of Technology Guwahati": 43,
  "Indian Institute of Technology Kanpur": 42,
  "Indian Institute of Technology Ropar": 47,
  "National Data Centre Shastri Park": 45,
  "NIC Nagaland State Centre Kohima": 50,
  "NISG Bhubaneswar": 52,
};
